### ISSUE TITLE
Add ability to switch between logging and printing

### ISSUE THREAD

**Issue by khanu263** [oresat/oresat-star-tracker-software#13]
Since the star tracker runs as a daemon, all output is sent to `/var/log/syslog`. This makes rapid implementation / debugging a pain. There should be some mechanism where the user can specify whether output should be logged or sent to `stdout`.

This will also require some re-tooling of `main.py` since it automatically redirects `stdout` to `/dev/null`. Ultimately this may mean adding some sort of switch between "daemon" and "user" modes.

**Comment by ryanpdx** [comment]
no longer needed
