### ISSUE TITLE
Test with simulated image set

### ISSUE THREAD

**Issue by khanu263** [oresat/oresat-star-tracker-software#14]
[Here's](https://drive.google.com/file/d/1qxiE2AIKs3oHplw-ups5NInVHyN0seRW/view?usp=sharing) a folder with 10,000 simulated images of stars. They were made by taking 2500 random captures from KStars (with settings eyeballed to approximately match what we get from our camera) and applying four random transformations (rotations, blurs, etc.) to each source image. There's a file called `log.txt` which described exactly what has happened in each image.

We need to run all of these through `solve-field` and OpenStarTracker, and then compare the results. This will probably involve adding some automated testing functionality to the code.

**Comment by ryanpdx** [comment]
No longer relevant, as we use LOST now
